/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";

import { useHover, useSetExhibit } from "../store/MetaStore";
import Router from "next/router";

export function PortalWorld(props) {
  const { scene, nodes } = useGLTF("/world/world17.glb");
  const [hover, setHover] = useHover((state) => [state.hover, state.setHover]);
  const [exhibit, setExhibit] = useSetExhibit((state) => [
    state.exhibit,
    state.setExhibit,
  ]);

  const handleHoverIn = (element) => {
    if (element.distance <= 15) {
      setHover(true);
    }
  };
  const handleHoverOut = () => {
    setHover(false);
  };

  return (
    <group scale={0.1} {...props} dispose={null}>
      <primitive object={scene} />
      <primitive
        dispose={null}
        object={nodes.frame01}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Mieke Marple",
            title: "Medusa 536",
            description:
              "Medusa 536 is part of the Marple's Medusa Collection, a set of unique generative NFTs reframing the Medusa myth. The collection, made using a combination of analog and digital techniques, is based on Marple’s paintings of canonical Italian sculptures of Medusa. Medusa 536, specifically, is based on Gian Lorenzo's bust of Medusa from 1640. Marple has been working with Medusa as a subject since discovernig that —  according to Ovid’s Metamorphoses from 8 AD — Medusa was raped by the god Poseidon and then turned into a monster by his wife, the god Athena. That this part of the story is rarely discussed felt indicative of the way countless groups are marginalized in the tales we take for granted as “history.",
            imageURL: "/show/01.jpg",
            URL: "https://opensea.io/assets/ethereum/0x259cf26dd6172728c6f8e0e6ae5b16e1b9d65df6/536",
            width: 547,
            height: 703,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame02}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Chole Karayia",
            title: "Cyber Skin",
            description: "A digital servant, friend or self reflection?",
            imageURL: "/show/02.jpg",
            URL: "",
            width: 800,
            height: 800,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame03}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: false,
            artist: "Carrie Able",
            title: "symbiosis",
            description: "Virtual Reality painting still image. ",
            imageURL: "/show/03.jpg",
            URL: "",
            width: 812,
            height: 812,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame04}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Aguri Sagimori",
            title: "MMMME – Sapph – ",
            description:
              '""MMMME"" is a chimera with four eyes, a fusion of human and cat."',
            imageURL: "/show/04.jpg",
            URL: "",
            width: 624,
            height: 811,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame05}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Operator",
            title: "Line Scanner (Herbert W. Franke Tribute Edition)",
            description:
              "Line Scanner (Herbert W. Franke Tribute Edition) is an excerpt from Line Scanner (2016), the first artwork by Ania Catherine and Dejha Ti, known as Operator. Line Scanner merges computer graphics and performance; it was created through Dejha Ti live triggering animations, video mapped onto Ania Catherine’s improvised movement from a projector suspended 11 meters above. The full length version of Line Scanner has been exhibited at CICA Museum in Korea, CADAF NYC, and film festivals internationally.          This edition is released on the occasion of the Tribute to Herbert W. Franke, as it realizes Franke's observation made decades earlier that ...the emergence of computer graphics could lead into other, quite different directions, for instance to unconventional, nondeterministic forms of theater (Computer Graphics — Computer Art, 1971).",
            imageURL: "/show/05.jpg",
            URL: "https://www.operator.la/line-scanner-hwf",
            width: 802,
            height: 802,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame06}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Anne Spalter",
            title: "Karyk",
            description:
              "We float untethered in a corporate metaverse, ungrounded and drifting, digitally painted and virtually constructed. How do we see ourselves reflected back in and through the screens we stare at all day? Combining my ongoing work with inflatables and industrial landscapes I have been developing a series of metaversal avatars, at once playful and slightly menacing, brightly colored but ominous in their rudimentary forms. Each is an alter ego, a companion, a manifestation made of air and pixels and electricity.",
            imageURL: "/show/06.jpg",
            URL: "",
            width: 794,
            height: 455,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame07}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "The Josh Craig",
            title: "[SHCA001] SPACE+TIME+ZERO",
            description: " A chromatic representation of an optical illusion",
            imageURL: "/show/07.jpg",
            URL: "",
            width: 603,
            height: 813,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame08}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Ana María Caballero",
            title: "Fathomless",
            description:
              "A spoken-word poem by award-winning poet + artist Ana María Caballero that weaves in and out of the tangled matrix of parental fear, without seeking to map it. From Caballero’s “Ways to Misspell Obsidian” collection, created in partnership with acclaimed London art gallery GAZELL.iO.",
            imageURL: "/show/08.jpg",
            URL: "https://nft.gazell.io/products/fathomless-1",
            width: 806,
            height: 808,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.sign01}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
        dispose={null}
      />

      <primitive
        object={nodes.sign02}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
      />
      <primitive
        object={nodes.sign03}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
        dispose={null}
      />

      <primitive
        object={nodes.sign04}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
      />
      <primitive
        object={nodes.sign05}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
        dispose={null}
      />

      <primitive
        object={nodes.sign06}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
      />
    </group>
  );
}

useGLTF.preload("/world/world09.glb");
