/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function PortalWorld(props) {
  const { nodes, materials } = useGLTF('/portalworld12.glb');
  return (
    <group scale={0.1} {...props} dispose={null}>
      <mesh geometry={nodes.portal.geometry} material={materials.portal} position={[-0.67, 22.6, -0.92]} />
      <group position={[0, -1.08, 0]} scale={-726.03}>
        <mesh geometry={nodes.ground_1.geometry} material={materials.groundtexture} />
        <mesh geometry={nodes.ground_2.geometry} material={materials.black} />
      </group>
      <group position={[41, -1.58, -169.39]} scale={3.16}>
        <mesh geometry={nodes.crystals_1.geometry} material={materials.pinkcrystal} />
        <mesh geometry={nodes.crystals_2.geometry} material={materials.purplecrystal} />
        <mesh geometry={nodes.crystals_3.geometry} material={materials.yellowcrystals} />
      </group>
      <mesh
        geometry={nodes.spinningcrystal.geometry}
        material={materials.preciousgem}
        position={[0.46, 20.49, -116.24]}
        scale={1.04}
      />
      <mesh
        geometry={nodes.column03.geometry}
        material={materials.column03}
        position={[28.32, 1.27, -25.35]}
        rotation={[0, 0, 0.14]}
        scale={[2.91, 3.26, 2.87]}
      />
      <mesh
        geometry={nodes.column01.geometry}
        material={materials.bakedrockcolumn}
        position={[-63.53, 2.11, -25.06]}
        scale={[2.91, 3.26, 2.87]}
      />
      <group position={[-24.9, 1.4, 64.46]} rotation={[-2.58, -0.25, 2.77]} scale={[3.43, 3.26, 3.37]}>
        <mesh geometry={nodes.column04_1.geometry} material={materials.column04} />
        <mesh geometry={nodes.column04_2.geometry} material={materials.miscrock02} />
      </group>
      <mesh
        geometry={nodes.column02.geometry}
        material={materials.column02}
        position={[39.54, 3.91, 50.7]}
        scale={[2.91, 3.26, 2.87]}
      />
      <mesh
        geometry={nodes.small_stones.geometry}
        material={materials.smallstones}
        position={[-15.92, 1.95, 90.51]}
        rotation={[0, 0, 1.78]}
        scale={[2.91, 3.26, 2.87]}
      />
      <mesh
        geometry={nodes.randomrocks.geometry}
        material={materials.randomrocks}
        position={[-93.19, -1.88, -179.15]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.mediumrocks.geometry}
        material={materials['medium rocks']}
        position={[-82.93, -1.11, -81.77]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.path01.geometry}
        material={materials.path01}
        position={[5.49, -1.14, 11.7]}
        scale={[2.48, 0.53, 2.48]}
      />
      <mesh
        geometry={nodes.path03.geometry}
        material={materials.path03}
        position={[-3.37, -1.69, -15.81]}
        rotation={[-3.12, -0.01, -3.14]}
        scale={[2.48, 0.53, 2.48]}
      />
      <mesh
        geometry={nodes.path04.geometry}
        material={materials.path04}
        position={[124.58, -2.19, 6.84]}
        rotation={[-1.79, -1.55, -1.79]}
        scale={[2.48, 0.53, 2.48]}
      />
      <mesh
        geometry={nodes.path02.geometry}
        material={materials.path02woops}
        position={[-123.39, -1.74, -0.98]}
        rotation={[-1.79, -1.55, -1.79]}
        scale={[2.48, 0.53, 2.48]}
      />
      <mesh
        geometry={nodes.epicrocks.geometry}
        material={materials['epic rocks']}
        position={[-192.69, -1.1, -23.94]}
        rotation={[1.64, 0, -Math.PI / 2]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.rockwithdiamond.geometry}
        material={materials.rockwithdiamond}
        position={[-0.37, -1.22, -116.42]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.03}
      />
      <group position={[-1.89, 28.7, -0.68]} rotation={[Math.PI, 0, Math.PI]} scale={5.67}>
        <mesh geometry={nodes.body_1.geometry} material={materials.skin} />
        <mesh geometry={nodes.body_2.geometry} material={materials.Hair_Boy30_Mat} />
      </group>
      <mesh
        geometry={nodes.egginner.geometry}
        material={materials.egg}
        position={[-1.8, 38.64, -2.39]}
        rotation={[0.07, 0, 0]}
        scale={[-5.75, -11.52, -5.75]}
      />
      <mesh
        geometry={nodes.eggouter.geometry}
        material={materials.egg01}
        position={[-1.8, 38.64, -2.39]}
        rotation={[0.07, 0, 0]}
        scale={[-5.75, -11.52, -5.75]}
      />
      <mesh
        geometry={nodes.tree.geometry}
        material={materials.deadtree}
        position={[102.51, 0, 145.81]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.14}
      />
      <mesh
        geometry={nodes.tree01.geometry}
        material={materials['deadtree.01']}
        position={[-118.02, 0, -48.99]}
        rotation={[Math.PI / 2, 0, 1.72]}
        scale={0.13}
      />
      <mesh
        geometry={nodes.tree02.geometry}
        material={materials.deadtree}
        position={[-107.93, -2.61, -171]}
        rotation={[Math.PI / 2, 0, -2.39]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.tree03.geometry}
        material={materials.deadtree}
        position={[142.1, -3.22, -89.36]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.skull.geometry}
        material={materials.skully}
        position={[101.22, 0, -23.44]}
        rotation={[Math.PI / 2, 0, -0.51]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.vines02.geometry}
        material={materials.deadtree}
        position={[-10.31, -4.15, -181.59]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.vines03.geometry}
        material={materials.deadtree}
        position={[24.44, -4.15, -176.87]}
        rotation={[Math.PI / 2, 0, -1.45]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.bush.geometry}
        material={materials.deadtree}
        position={[-138.23, -13.61, 113.06]}
        rotation={[1.6, 0.09, -1.12]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.vines.geometry}
        material={materials.mossy}
        position={[-60.25, -0.55, 28.11]}
        rotation={[Math.PI / 2, 0, 2.37]}
        scale={0.03}
      />
    </group>
  );
}

useGLTF.preload('/portalworld12.glb');
