/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useEffect, useState } from "react";

export function PortalWorld(props) {
  const [frame01, setFrame01] = useState(null);
  const { scene, nodes, materials } = useGLTF("/portalworld16.glb");

  useEffect(() => {
    setFrame01(scene.getObjectByName("frame01"));
  }, [scene]);

  return (
    <group scale={0.1} {...props} dispose={null}>
      <primitive object={scene} />
      {frame01 && (
        <primitive object={frame01} onClick={() => console.log("worked")} />
      )}
    </group>
  );
}

useGLTF.preload("/portalworld16.glb");
