/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PortalWorld(props) {
  const { scene, nodes, materials } = useGLTF("/portalworld15.glb");
  return <primitive object={scene} scale={0.1} />;
}

useGLTF.preload("/portalworld15.glb");
