/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PortalWorld(props) {
  const { scene, nodes, materials } = useGLTF("/portalworld13.glb");
  return (
    <group scale={0.1} {...props} dispose={null}>
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload("/portalworld13.glb");
