/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Terrain(props) {
  const { nodes, materials } = useGLTF('/terrain01.glb');
  return (
    <group {...props} dispose={null} scale={0.5}>
      <mesh
        geometry={nodes.portal.geometry}
        material={materials['Material.001']}
        position={[7.25, -0.47, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.column.geometry} material={materials.STONE1} position={[16.95, 0.1, -11.42]} scale={1.41} />
      <mesh geometry={nodes.column1.geometry} material={materials.STONE1} position={[-13.16, -0.31, 10.3]} />
      <mesh geometry={nodes.column3.geometry} material={materials.STONE1} position={[19.08, 0.41, 7.75]} scale={1.71} />
      <mesh
        geometry={nodes.column4.geometry}
        material={materials.STONE1}
        position={[-12.88, 0.1, -10.96]}
        rotation={[0, -1.46, 0]}
        scale={1.41}
      />
      <mesh
        geometry={nodes.column2.geometry}
        material={materials.STONE1}
        position={[1.28, 0.28, -23.48]}
        scale={1.71}
      />
      <mesh geometry={nodes.ground.geometry} material={materials.GROUND} scale={-181.41} />
    </group>
  );
}

useGLTF.preload('/terrain01.glb');
