/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import { useFrame } from "@react-three/fiber";

export function Ghost(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/animatedghost01.glb");
  const { actions } = useAnimations(animations, group);

  useFrame((state, delta) => {
    group.current.position.y = -4;
  });

  return (
    <group ref={group} {...props} dispose={null} scale={4}>
      <group name="Scene">
        <group
          name="Armature"
          position={[0, 1.46, -0.02]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={-0.22}
        >
          <primitive object={nodes.Bone} />
          <primitive object={nodes.neutral_bone} />
          <group name="hoodie">
            <skinnedMesh
              name="the_hoodie06002"
              geometry={nodes.the_hoodie06002.geometry}
              material={materials["lowpoly fabric"]}
              skeleton={nodes.the_hoodie06002.skeleton}
            />
            <skinnedMesh
              name="the_hoodie06002_1"
              geometry={nodes.the_hoodie06002_1.geometry}
              material={materials["frown face"]}
              skeleton={nodes.the_hoodie06002_1.skeleton}
            />
            <skinnedMesh
              name="the_hoodie06002_2"
              geometry={nodes.the_hoodie06002_2.geometry}
              material={materials["lowpoly fabric"]}
              skeleton={nodes.the_hoodie06002_2.skeleton}
            />
          </group>
        </group>
        <mesh
          name="mask"
          geometry={nodes.mask.geometry}
          material={materials["mask skin"]}
          position={[0, 0, -0.05]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/animatedghost01.glb");
