/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Shiloh(props) {
  const { nodes, materials } = useGLTF("/shiloh1.glb");
  const group = useRef();

  useFrame((state, delta) => {
    group.current.position.y = 0;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      {/* <pointLight /> */}
      <group rotation={[Math.PI, 0, Math.PI]} scale={0.5}>
        <mesh
          geometry={nodes.body_1.geometry}
          material={materials["JA LENS.008"]}
        />
        <mesh
          geometry={nodes.body_2.geometry}
          material={materials["JA EYES.008"]}
        />
        <mesh geometry={nodes.body_3.geometry} material={materials.Face} />
        <mesh geometry={nodes.body_4.geometry} material={materials.Arms} />
        <mesh geometry={nodes.body_5.geometry} material={materials.Torso} />
        <mesh
          geometry={nodes.body_6.geometry}
          material={materials["Eyelashes Layer B.001"]}
        />
        <mesh
          geometry={nodes.body_7.geometry}
          material={materials["Eyelashes Layer A.001"]}
        />
        <mesh
          geometry={nodes.body_8.geometry}
          material={materials.EyeMoisture}
        />
        <mesh
          geometry={nodes.body_9.geometry}
          material={materials["JA_Brows.008"]}
        />
        <mesh geometry={nodes.body_10.geometry} material={materials.Lips} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          geometry={nodes.hood_1.geometry}
          material={materials["Knit_Fleece_Terry BRUSHED_FRONT_2745"]}
        />
        <mesh
          geometry={nodes.hood_2.geometry}
          material={materials["Knit_Fleece_Terry BRUSHED_FRONT_2745"]}
        />
        <mesh
          geometry={nodes.hood_3.geometry}
          material={materials["frown face.001"]}
        />
      </group>
      <mesh
        geometry={nodes.hair.geometry}
        material={materials.Hair_Boy30_Mat}
        scale={[0.13, 0.14, 0.13]}
      />
      <mesh
        geometry={nodes.pants.geometry}
        material={materials.pants}
        scale={0.01}
      />
      <mesh
        geometry={nodes.shoes.geometry}
        material={materials["white shoe"]}
        rotation={[1.56, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/shiloh1.glb");
