/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PresentationControls } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Shiloh(props) {
  const { nodes, materials } = useGLTF("/shiloh02.glb");

  const bgRef = useRef();
  const lightRef = useRef();
  const shilohRef = useRef();

  useFrame((state, delta) => {
    bgRef.current.position.y = -0.5;
    bgRef.current.position.x = -1.5;
    shilohRef.current.position.y = -1.5;

    lightRef.current.position.z += Math.sin(delta * 8);

    const t = state.clock.getElapsedTime();

    shilohRef.current.rotation.y = Math.sin(t / 4) / 8;
    // shilohRef.current.rotation.z = (1 + Math.sin(t / 1.5)) / 20;
    // shilohRef.current.position.y = (1 + Math.sin(t / 1.5)) / 10;
  });

  return (
    <>
      <group ref={shilohRef} {...props} dispose={null}>
        <mesh
          ref={bgRef}
          geometry={nodes.forest_still.geometry}
          material={materials["forest still"]}
          position={[-0.62, 1.95, -1.11]}
          rotation={[Math.PI / 2, 0, -0.55]}
          scale={3.97}
        />
        <PresentationControls
          global
          config={{ mass: 2, tension: 500 }}
          snap={{ mass: 4, tension: 1500 }}
          rotation={[0, 0.3, 0]}
          polar={[-Math.PI / 3, Math.PI / 3]}
          azimuth={[-Math.PI / 1.4, Math.PI / 2]}
        >
          <mesh
            geometry={nodes.hoodie_bands.geometry}
            material={materials["hoodie bands"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.hoodie_sleeves_and_back.geometry}
            material={materials["hoodie sleeves and back"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.hoodie_front.geometry}
            material={materials.frowny}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.Mesh002.geometry}
              material={materials["JA LENS.008"]}
            />
            <mesh
              geometry={nodes.Mesh002_1.geometry}
              material={materials["JA EYES.008"]}
            />
            <pointLight ref={lightRef} intensity={1.2} color={"white"} />
            <mesh
              geometry={nodes.Mesh002_2.geometry}
              material={materials.skin}
            />
            <mesh
              geometry={nodes.Mesh002_3.geometry}
              material={materials.hands}
            />
          </group>
          <mesh
            geometry={nodes.brows.geometry}
            material={materials["JA_Brows.001"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.hair.geometry}
            material={materials.Hair_Boy30_Mat}
            position={[0, 0.76, -0.03]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.13, 0.14, 0.13]}
          />
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.Mesh001.geometry}
              material={materials["EyeMoisture.003"]}
            />
            <mesh
              geometry={nodes.Mesh001_1.geometry}
              material={materials["Eyelashes Layer A.001"]}
            />
            <mesh
              geometry={nodes.Mesh001_2.geometry}
              material={materials["Eyelashes Layer B.001"]}
            />
          </group>
          <mesh
            geometry={nodes.pants.geometry}
            material={materials.pants}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.shoes.geometry}
            material={materials.shoe}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
        </PresentationControls>
      </group>
    </>
  );
}

useGLTF.preload("/shiloh02.glb");
