/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PresentationControls } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Shiloh(props) {
  const { scene } = useGLTF("/shiloh06.glb");

  const forest = scene.getObjectByName("forest_still");

  const shilohRef = useRef();

  useFrame((state, delta) => {
    shilohRef.current.position.y = -1.5;

    forest.position.y = 2.2;
    forest.position.z = -2.5;

    const t = state.clock.getElapsedTime();
    const { mouse } = state;
    shilohRef.current.rotation.y = Math.sin(t / 10) / 8 + mouse.x * 0.01;
    shilohRef.current.position.y = -1.3 + (1 + Math.sin(t / 1.5)) / 100;
  });
  return (
    <>
      <group {...props} dispose={null} ref={shilohRef}>
        <primitive object={scene} />
      </group>
    </>
  );
}

useGLTF.preload("/shiloh06.glb");
