/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useEffect, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useFrame, useGraph } from "@react-three/fiber";
import { useInputs } from "../input/input-controller";
import * as THREE from "three";

export function Ghost(props) {
  const [walking, setWalking] = useState(false);

  const group = useRef();
  const hoodie = useRef();
  const mask = useRef();

  const { scene, materials, animations } = useGLTF("/ghostCopy.glb");

  const { actions } = useAnimations(animations, group);

  const input = useInputs();

  useEffect(() => {
    if (walking) {
      actions?.walk.play();
    }
    if (!walking) {
      actions?.walk.stop();
      actions?.idle.play();
    }
  }, [walking]);

  useFrame(() => {
    setWalking(false);
    if (props.singleWalking === true) {
      setWalking(true);
    }
    hoodie.current.material.color.set(props.color);

    mask.current.material.color.set("white");
  });

  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone);
  return (
    <group ref={group} {...props} dispose={null} scale={0.35}>
      <group name="Scene">
        <group
          name="Armature"
          position={[0, 0.81, -0.01]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            ref={hoodie}
            name="hoodie"
            geometry={nodes.hoodie.geometry}
            material={new THREE.MeshPhongMaterial()}
            // material={materials['lowpoly fabric']}
            skeleton={nodes.hoodie.skeleton}
          />
          <skinnedMesh
            ref={mask}
            name="mask"
            geometry={nodes.mask.geometry}
            material={materials["mask skin"]}
            skeleton={nodes.mask.skeleton}
          />
        </group>
        <mesh
          name="egg"
          geometry={nodes.egg.geometry}
          material={materials.egg}
          position={[0, 0.71, 0.08]}
          scale={[0.52, 0.88, 0.52]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ghost10.glb");
