/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Ghost(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/ghost09.glb');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null} scale={0.3}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="hoodie"
            geometry={nodes.hoodie.geometry}
            material={materials['lowpoly fabric']}
            skeleton={nodes.hoodie.skeleton}
          />
          <skinnedMesh
            name="mask"
            geometry={nodes.mask.geometry}
            material={materials['mask skin']}
            skeleton={nodes.mask.skeleton}
          />
        </group>
      </group>
      <mesh name="cube" geometry={nodes.cube.geometry} color={'red'} position={[0, 0.9, 0]} scale={[0.2, 0.62, 0.2]} />
    </group>
  );
}

useGLTF.preload('/ghost09.glb');
