/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useEffect, useState } from "react";
import { useGLTF, useAnimations, Billboard, Text } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useFrame, useGraph } from "@react-three/fiber";
import { useInputs } from "../input/input-controller";
import * as THREE from "three";
import { useCustomColor, useCustomName } from "../store/MetaStore";

export function Ghost(props) {
  const [walking, setWalking] = useState(false);
  const color = useCustomColor((state) => [state.customColor]);
  const [userName, setUserName] = useCustomName((state) => [
    state.userName,
    state.setUserName,
  ]);

  const group = useRef();
  const hoodie = useRef();
  const mask = useRef();
  const textRef = useRef();

  const { scene, materials, animations } = useGLTF("/ghost10.glb");

  const { actions } = useAnimations(animations, group);

  const input = useInputs();

  useEffect(() => {
    if (walking) {
      actions?.walk.play();
    }
    if (!walking) {
      actions?.walk.stop();
      actions?.idle.play();
    }
  }, [walking]);

  useFrame(() => {
    const { move } = input;

    setWalking(false);
    if (move.x !== 0 || move.y !== 0) {
      setWalking(true);
    }
    textRef.current.position.y = hoodie.current.position.y + 1.85;
    // group.current.position.y = -0.5;

    // mask.current.material.color.set(`${color}`);
    mask.current.material.transparent = true;
    // mask.current.material.opacity = 0.8;

    hoodie.current.material.color.set(`${color}`);
    // hoodie.current.material.transparent = true;
    // hoodie.current.material.opacity = 0.8;
    group.current.position.y = -0.1;
  });

  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone);
  return (
    <>
      <group ref={group} {...props} dispose={null} scale={0.35}>
        <group ref={textRef}>
          <Billboard
            follow={true}
            lockX={false}
            lockY={false}
            lockZ={false} // Lock the rotation on the z axis (default=false)
          >
            <Text anchorY="top" fontSize={0.15}>
              {userName ? userName : "Shiloh"}
            </Text>
          </Billboard>
        </group>
        <group name="Scene">
          <group
            name="Armature"
            position={[0, 0.81, -0.01]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <primitive object={nodes.mixamorigHips} />
            <skinnedMesh
              ref={hoodie}
              name="hoodie"
              geometry={nodes.hoodie.geometry}
              material={materials["lowpoly fabric"]}
              skeleton={nodes.hoodie.skeleton}
            />
            <skinnedMesh
              ref={mask}
              name="mask"
              geometry={nodes.mask.geometry}
              material={materials["mask skin"]}
              skeleton={nodes.mask.skeleton}
            />
          </group>
          <mesh
            name="egg"
            geometry={nodes.egg.geometry}
            material={materials.egg}
            position={[0, 0.71, 0.08]}
            scale={[0.52, 0.88, 0.52]}
          />
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/ghost10.glb");
