/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

export function Ghost(props) {
  const { nodes, materials } = useGLTF('/ghosttest03.gltf');

  useEffect(() => {
    var tex = new THREE.TextureLoader().load('/mask2.jpg');
    tex.flipY = false;
    // materials.mask.map = tex;
    var randomColor = Math.floor(Math.random() * 16777215).toString(16);
    console.log(materials.white);
    materials.white.color.setRGB(Math.random(), Math.random(), Math.random());

    console.log(randomColor);
  }, []);
  return (
    <group {...props} dispose={null} scale={0.1}>
      <group position={[0.04, 2.53, 0]} scale={0.18}>
        <mesh geometry={nodes.pCylinder1_ghost_0.geometry} material={materials.white} />
        <mesh geometry={nodes.pCylinder1_ghost_0_1.geometry} material={materials.frame} />
      </group>
      <group position={[0, 4.65, 0.68]} rotation={[-0.19, 0, 0]} scale={[0.57, 0.57, 0.28]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.teeth} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.mask} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.frame} />
      </group>
    </group>
  );
}

useGLTF.preload('/ghosttest03.gltf');
