/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";

import { useHover, useSetExhibit } from "../store/MetaStore";
import Router from "next/router";

export function PortalWorld(props) {
  const { scene, nodes } = useGLTF("/world/world14.glb");
  const [hover, setHover] = useHover((state) => [state.hover, state.setHover]);
  const [exhibit, setExhibit] = useSetExhibit((state) => [
    state.exhibit,
    state.setExhibit,
  ]);

  const handleHoverIn = (element) => {
    if (element.distance <= 15) {
      setHover(true);
    }
  };
  const handleHoverOut = () => {
    setHover(false);
  };

  return (
    <group scale={0.1} {...props} dispose={null}>
      <primitive object={scene} />
      <primitive
        dispose={null}
        object={nodes.frame01}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Tripura",
            title: "Hydra",
            description:
              "My work is primarily concerned with the theme of nature-human interaction. This particular project is devoted to the topic of human physicality. Such modern philosophers as Yuval Arari and Daniel Kahneman believe that in the near future technology is expected to become a significant part of our new physicality: their opinion is based on the fact that the current rate of change in the human world is occurring at an exponentially increasingly pace. In my pieces, I propose an alternative scenario, where the human body develops not in the technological direction, but rather a natural symbiosis, resulting in the synthesis of new life forms - no longer human, though not yet plant or animal: but a borderline form.",
            imageURL: "/show/01.jpg",
            URL: "https://app.manifold.xyz/c/Tripura-edition",
            width: 822,
            height: 1460,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame02}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Tabitha Swanson & Balfua",
            title: "twytholemew's mask in the glass flame grass patch of shame",
            description:
              "1 of 8 mystical totems rendered by tabitha swanson and balfua, created utilizing virtual reality modeling and blender with special ancient unknown techniques",
            imageURL: "/show/02.jpg",
            URL: "https://objkt.com/asset/KT1EPzDE4JKWK3EBy46rm3JaWfMVbvWaTkjh/0",
            width: 2000,
            height: 2000,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame03}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Violet Forest",
            title: "Silk ‧͙⁺˚ ⁺ Satin ‧͙⁺˚ ⁺ Flowers ‧͙⁺˚ ⁺ Melted Wax",
            description: "GAN generated 2048 x 2048 9 seconds looping",
            imageURL: "/show/03.jpg",
            URL: "https://foundation.app/@violetforest/foundation/93005",
            width: 504,
            height: 507,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame04}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Megan Majewski",
            title: "Quiet Reflection",
            description:
              "My pieces from the Poetry of Flowers collection, speak on themes of life, death and reincarnation while using the language of flowers.",
            imageURL: "/show/04.jpg",
            URL: "https://foundation.app/@deadkittie/Poetry-of-flowers/1",
            width: 461,
            height: 459,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame05}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Nicoleta Mureş",
            title: "Last Coffee",
            description:
              "These strange creatures,  inhabitants of the personal profile with personalized avatars, are constantly feeding on their feed. They are the weavers of the WWW, which is likely to be a dangerous and potentially toxic mix of rumour, gossip, conspiracy, lies and misinformation.",
            imageURL: "/show/05.jpg",
            URL: "https://www.voice.com/creation/200000000003855",
            width: 1920,
            height: 1663,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame06}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: false,
            artist: "Formless",
            title: "Who wrote our song by Taylor Swift?",
            description: "It's all mine",
            imageURL: "/show/06.jpg",
            URL: "https://foundation.app/@formless/spit/7",
            width: 828,
            height: 465,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame07}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Maritei",
            title: "Cyber Angel",
            description:
              "The fist piece I ever minted, in 2020. The advent of a Love Apocalypse ",
            imageURL: "/show/07.jpg",
            URL: "https://foundation.app/@mariteiei/foundation/71614",
            width: 423,
            height: 508,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame08}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            artist: "Saida Saetgar",
            title: "Artificial Soul",
            description:
              "Artificial soul is a lab-grown digital entity that represents a midpoint between plant and intelligent cyborg. With its unique features, it offers a communication experience unlike any other. Its vibrant colored signals and fluid-like intelligent haptic system serve as a language of their own, sensing your mood and adapting accordingly at every moment.",
            imageURL: "/show/08.jpg",
            URL: "https://www.instagram.com/p/CLNVmkiH-J_/?next=%2F",
            width: 606,
            height: 755,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.sign01}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
        dispose={null}
      />

      <primitive
        object={nodes.sign02}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
      />
      <primitive
        object={nodes.sign03}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
        dispose={null}
      />

      <primitive
        object={nodes.sign04}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
      />
      <primitive
        object={nodes.sign05}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
        dispose={null}
      />

      <primitive
        object={nodes.sign06}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
      />
    </group>
  );
}

useGLTF.preload("/world/world09.glb");
