/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";

import { useHover, useSetExhibit } from "../store/MetaStore";
import Router from "next/router";

export function PortalWorld(props) {
  const { scene, nodes } = useGLTF("/world/world09.glb");
  const [hover, setHover] = useHover((state) => [state.hover, state.setHover]);
  const [exhibit, setExhibit] = useSetExhibit((state) => [
    state.exhibit,
    state.setExhibit,
  ]);

  const handleHoverIn = () => {
    setHover(true);
  };
  const handleHoverOut = () => {
    setHover(false);
  };

  return (
    <group scale={0.1} {...props} dispose={null}>
      <primitive object={scene} />
      <primitive
        dispose={null}
        object={nodes.frame01}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: false,
            title: "Planetary Alignment",
            description:
              "This piece is emblematic of the recurring elements in the artist's work, symbolized as a planet; as every creator is the author of their own world.",
            artist: "Carmilla Sumantry",
            imageURL: "/show/01.jpg",
            URL: "https://superrare.com/0xe9ff2190f3832936d4b9919b71cef39eb13a4757/planetary-alignment-1",
            width: 1447,
            height: 811,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame02}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            title: "SHORT TERM MEMORIES",
            description:
              "1800x2700 px | 00:36 mp4 | 2018 | Unique Sound design @raum_antibodylabel",
            artist: "Olga Fedorova",
            imageURL: "/show/02.png",
            URL: "https://foundation.app/@olgamikhfedorova/foundation/113570",
            width: 175,
            height: 256,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame03}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: false,
            title: "Hiru",
            description:
              "'Hiru' is an audio visual exploration of a life cycle of consciousness.",
            artist: "Ellie Pritts",
            imageURL: "/show/03.jpg",
            URL: "https://superrare.com/0xd8c9c3a2724e703c0ca7d205f16aff8acaac9994/hiru-5",
            width: 1331,
            height: 753,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame04}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            title: "BizBuyer",
            description:
              "This piece is one of the 490 AI-generated logos from Dotcom Séance. A project that utilized the sacred powers of AI and web3.0 to resurrect the dead companies from the infamous dotcom crash.",
            artist: "Guile Twardowski",
            imageURL: "/show/04.jpg",
            URL: "https://opensea.io/assets/ethereum/0x6ca044fb1cd505c1db4ef7332e73a236ad6cb71c/420",
            width: 804,
            height: 805,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame05}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            title: "i luv the way you care about my gardens",
            description: "2022 |ambient music by Charly Pœ |2500x2160 px",
            artist: "Simone Garcia",
            imageURL: "/show/05.jpg",
            URL: "https://superrare.com/artwork-v2/i-luv-the-way-you-care-about-my-gardens-34423",
            width: 470,
            height: 485,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame06}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: false,
            title: "Out of Gas and Desperate for Love",
            description: "resolution: 2160 x 2700px duration: 20s year: 2022",
            artist: "Parsa Mostaghim",
            imageURL: "/show/06.jpg",
            URL: "https://foundation.app/@parsa.mostaghim/everyday/18",
            width: 866,
            height: 690,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame07}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: true,
            title: "AI is watching",
            description: "What do you see in the changing world around us?",
            artist: "Rutger van der Tas ",
            imageURL: "/show/07.jpg",
            URL: "https://objkt.com/asset/KT19gfyncsoejGLy8YnVAZTXKAzjSACgr9vB/0",
            width: 275,
            height: 490,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.frame08}
        onClick={() =>
          setExhibit({
            bool: true,
            portrait: false,
            title: "Seance",
            description:
              "Seance depicts 5 witches summoning the power of Hecate in a dark forest.",
            artist: "Cait Lamas",
            imageURL: "/show/08.jpg",
            URL: "https://foundation.app/@ghostrystore/cim-0c78/2",
            width: 852,
            height: 487,
          })
        }
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
      />

      <primitive
        object={nodes.sign01}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
        dispose={null}
      />

      <primitive
        object={nodes.sign02}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
      />
      <primitive
        object={nodes.sign03}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
        dispose={null}
      />

      <primitive
        object={nodes.sign04}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
      />
      <primitive
        object={nodes.sign05}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
        dispose={null}
      />

      <primitive
        object={nodes.sign06}
        onPointerOver={handleHoverIn}
        onPointerLeave={handleHoverOut}
        onClick={() => Router.push("/mint")}
      />
    </group>
  );
}

useGLTF.preload("/world/world09.glb");
